# Generated by Django 5.0.6 on 2024-05-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_event_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='activity',
            new_name='event',
        ),
    ]
